package example;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Tue Apr 24 11:09:38 PDT 2012
 */
public class BarristerMeta {

    public static final Long DATE_GENERATED = 1335290977376L;
    public static final String CHECKSUM = "51a911b5eb0b61fbb9300221d8c37134";
    public static final String BARRISTER_VERSION = "0.1.1";

}

