package example;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Thu Apr 12 15:01:42 PDT 2012
 */
public class BarristerMeta {

    public static final Long DATE_GENERATED = 1334268101661L;
    public static final String CHECKSUM = "51a911b5eb0b61fbb9300221d8c37134";
    public static final String BARRISTER_VERSION = "0.1.0";

}

