package example;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Wed Apr 25 13:34:17 PDT 2012
 */

public interface Calculator {

    public Double add(Double a, Double b) throws com.bitmechanic.barrister.RpcException;
    public Double subtract(Double a, Double b) throws com.bitmechanic.barrister.RpcException;

}

