package example;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Wed Apr 25 12:27:40 PDT 2012
 */
public class BarristerMeta {

    public static final Long DATE_GENERATED = 1335382060067L;
    public static final String CHECKSUM = "534c89cad165118ef9ad62b294442e1d";
    public static final String BARRISTER_VERSION = "0.1.1";

}

