package example;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Thu Apr 12 15:01:28 PDT 2012
 */
public class BarristerMeta {

    public static final Long DATE_GENERATED = 1334268087454L;
    public static final String CHECKSUM = "534c89cad165118ef9ad62b294442e1d";
    public static final String BARRISTER_VERSION = "0.1.0";

}

