package example;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Wed Apr 25 12:27:40 PDT 2012
 */

public interface Echo {

    public String echo(String s) throws com.bitmechanic.barrister.RpcException;

}

