package example;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Thu Apr 12 15:01:28 PDT 2012
 */

public interface Echo {

    public String echo(String s) throws com.bitmechanic.barrister.RpcException;

}

